# Generated by Django 4.2.28 on 2026-03-02 15:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('total_cpu', models.IntegerField()),
                ('total_ram', models.IntegerField()),
                ('total_disk', models.BigIntegerField()),
                ('labels', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'infrastructure.hosts',
            },
        ),
        migrations.CreateModel(
            name='HostSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('used_cpu', models.FloatField()),
                ('used_ram', models.IntegerField()),
                ('used_disk', models.BigIntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.host')),
            ],
            options={
                'db_table': 'infrastructure.host_snapshots',
            },
        ),
    ]
