# Generated by Django 4.2.28 on 2026-03-02 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('project_id', models.UUIDField()),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('docker_container_id', models.CharField(blank=True, max_length=255, null=True)),
                ('host_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compute_service.virtual_machines',
            },
        ),
    ]
